import turtle
fred = turtle.Pen()
fred.width(5)

for i in range(1*250,500):
    fred.up()
    fred.right(700)
    fred.down()
    fred.color("black")
    fred.circle(1)
    fred.color("yellow")
    fred.circle(5)
    fred.color("blue")
    fred.circle(25)
    fred.color("red")
    fred.circle(50)
    fred.color("green")
    fred.circle(75)
    fred.color("orange")
    fred.circle(100)
    fred.color("pink")
    fred.circle(125)
    fred.color("purple")
    fred.circle(150)
    fred.color("yellow")
    fred.circle(175)
    fred.color("blue")
    fred.circle(200)
    fred.color("red")
    fred.circle(225)
    fred.color("green")
    fred.circle(250)
    fred.color("orange")
    fred.circle(275)
    fred.color("pink")
    fred.circle(300)
    fred.color("purple")
    fred.circle(400)
    fred.color("magenta")
    fred.circle(500)
